# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='testMessage2.proto',
  package='',
  serialized_pb='\n\x12testMessage2.proto\"5\n\tUserLogin\x12\x12\n\nclientName\x18\x01 \x02(\t\x12\x14\n\x0crequest_type\x18\x02 \x01(\t')




_USERLOGIN = descriptor.Descriptor(
  name='UserLogin',
  full_name='UserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='clientName', full_name='UserLogin.clientName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request_type', full_name='UserLogin.request_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['UserLogin'] = _USERLOGIN

class UserLogin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLOGIN
  
  # @@protoc_insertion_point(class_scope:UserLogin)

# @@protoc_insertion_point(module_scope)
